package simpledb.execution;

import simpledb.common.DbException;
import simpledb.storage.Field;
import simpledb.storage.Tuple;
import simpledb.storage.TupleDesc;
import simpledb.transaction.TransactionAbortedException;

import java.util.Iterator;
import java.util.NoSuchElementException;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    private JoinPredicate p;
    OpIterator child1;

    Tuple nextChild1;

    OpIterator child2;


    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     *
     * @param p      The predicate to use to join the children
     * @param child1 Iterator for the left(outer) relation to join
     * @param child2 Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        // TODO: some code goes here
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        this.nextChild1 = null;
    }

    public JoinPredicate getJoinPredicate() {
        // TODO: some code goes here
        return this.p;
    }

    /**
     * @return the field name of join field1. Should be quantified by
     *         alias or table name.
     */
    public String getJoinField1Name() {
        // TODO: some code goes here
        TupleDesc tupleDesc = this.child1.getTupleDesc();
        return tupleDesc.getFieldName(this.p.getField1());
    }

    /**
     * @return the field name of join field2. Should be quantified by
     *         alias or table name.
     */
    public String getJoinField2Name() {
        // TODO: some code goes here
        TupleDesc tupleDesc = this.child2.getTupleDesc();
        return tupleDesc.getFieldName(this.p.getField2());
    }

    /**
     * @see TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *         implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // TODO: some code goes here
        TupleDesc child1TupleDesc = this.child1.getTupleDesc();
        TupleDesc child2TupleDesc = this.child2.getTupleDesc();
        return TupleDesc.merge(child1TupleDesc, child2TupleDesc);
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // TODO: some code goes here
        // child1 is left relation
        this.child1.open();
        if (this.child1.hasNext()) {
            this.nextChild1 = this.child1.next();
        }
        this.child2.open();
        super.open();
    }

    public void close() {
        // TODO: some code goes here
        super.close();
        this.child1.close();
        this.nextChild1 = null;
        this.child2.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // TODO: some code goes here
        this.child1.rewind();
        if (this.child1.hasNext()) {
            this.nextChild1 = this.child1.next();
        }
        this.child2.rewind();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     *
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // TODO: some code goes here
        /**
         * Here the simplest join type is nested loop join
         */
        while (this.child2.hasNext()) {
            Tuple nextChild2 = this.child2.next();
            if (this.p.filter(nextChild1, nextChild2)) {
                TupleDesc newTupleDesc = this.getTupleDesc();
                Tuple newTuple = new Tuple(newTupleDesc);
                int child1Length = this.child1.getTupleDesc().numFields();

                for (int i = 0; i < newTupleDesc.numFields(); i++) {
                    if (i < child1Length) {
                        newTuple.setField(i, nextChild1.getField(i));
                    } else {
                        newTuple.setField(i, nextChild2.getField(i - child1Length));
                    }
                }
                return newTuple;
             }
        }

        if (!this.child1.hasNext()) {
            return null;
        } else {
            this.nextChild1 = child1.next();
            this.child2.rewind();
            return fetchNext();
        }
    }

    @Override
    public OpIterator[] getChildren() {
        // TODO: some code goes here
        return new OpIterator[]{this.child1, this.child2};
    }

    @Override
    public void setChildren(OpIterator[] children) {
        // TODO: some code goes here
        this.child1 = children[0];
        this.child2 = children[1];
    }

}
